spring:
  datasource:
    url: jdbc:mysql:///java_web_final_examination
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    prefix: classpath:/static/
logging:
    level:
      root: WARN
      org.springframework.web: trace
      com.yourpackage: DEBUG


